language: node_js
os:
  - linux
  - osx
node_js:
  - "7"
  - "6"
before_script: npm install -g yarn@0.18.0
script: yarn run setup
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
